# database config
database:
  driver: mysql # Database Drivers
  host: 172.16.222.36 # Host
  port: 3306 # Port
  username: root # Username
  password: 1100 # Password
  database: rgrpc-auth # Database
  charset: utf8mb4 # Charset
  maxIdleCons: 10 # Maximum number of connections in the idle connection pool
  maxOpenCons: 100 # Maximum number of open database connections
  logMode: info # Log level
  enableFileLogWriter: true # Whether to enable log files
  logFilename: sql.log # Log file name

# env
env: dev

# grpc config
grpc:
  host: ""
  port: ":50051"
  name: "auth-grpc"

# http config
http:
  host: ""
  port: ":9001"
  name: "auth-http"
