# service
apiVersion: v1
kind: Service
metadata:
  name: permission-gw
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: permission
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
---
# service
apiVersion: v1
kind: Service
metadata:
  name: permission-server
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: permission
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051

