// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"permissionservice/config"
	"permissionservice/genproto/v1"
	"permissionservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.PermissionServiceServer, error) {
	authServiceClient, err := service.NewAuthClient(conf)
	if err != nil {
		return nil, err
	}
	permissionServiceServer := service.NewServer(conf, authServiceClient)
	return permissionServiceServer, nil
}
