apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: jgrpc-dev
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: your-registry-secret
      containers:
        - name: ping
          image: REGISTRY_URL/PROJECT_NAME/IMAGE_NAME:IMAGE_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
            - containerPort: 50051
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime