# service
apiVersion: v1
kind: Service
metadata:
  name: ping-http
  namespace: jgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: ping
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
---
# service
apiVersion: v1
kind: Service
metadata:
  name: ping-rpc
  namespace: jgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: ping
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
