# virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jgrpc
  namespace: jgrpc-dev
spec:
  hosts:
    - "dev.api.your-domain.com"
  gateways:
    - jgrpc
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: ping